valentintournant/PAPEL

- app/models/cohort.rb
- db/migrate/20200825095706_create_cohorts.rb
- test/models/cohort_test.rb
Creation of the model Cohort with the reference of the user
> creation of the model cohort with the user's references

- app/models/receipt.rb
- config/routes.rb
- db/migrate/20200825100436_create_receipts.rb
- db/schema.rb
- test/models/receipt_test.rb
> receipt model

- app/models/user.rb
- db/schema.rb
Creation of the autorisation inside the models
> creation of the references inside the routes

- app/controllers/cohorts_controller.rb
- app/models/cohort.rb
- app/models/user.rb
- config/routes.rb
- db/schema.rb
- test/controllers/cohorts_controller_test.rb
Creation of the controller and the routes
> creation of the controller and the routes

- app/views/cohorts/index.html.erb
- app/views/shared/_navbar.html.erb
Creation of the index and the show index for cohorte
> creation of the index and the view fothe cohorte

- app/controllers/cohorts_controller.rb
- app/models/cohort.rb
- app/models/user.rb
- app/views/cohorts/index.html.erb
- app/views/shared/_navbar.html.erb
- db/seeds.rb
Creation of the seed for user and cohorte, 
Validation of 2 user storie:
- I can click on the "My groups" button and enter the Groups#index 
- I can read all my groups
> creation of the index, list, seed user an cohorte

- app/controllers/receipts_controller.rb
- app/models/cohort.rb
- app/models/receipt.rb
- app/views/receipts/edit.html.erb
- app/views/receipts/index.html.erb
- app/views/receipts/new.html.erb
- app/views/receipts/show.html.erb
- db/migrate/20200825122601_removes_cohort_null_false_to_receipts.rb
- db/schema.rb
- test/controllers/receipts_controller_test.rb
> Receipt controller

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_show.scss
- app/controllers/cohorts_controller.rb
- app/views/cohorts/_form.html.erb
- app/views/cohorts/edit.html.erb
- app/views/cohorts/new.html.erb
- app/views/cohorts/show.html.erb
Create all the method belongs to each user stories
Execpt for for the storie with the receipt need to update with Jule's work
> finish all the method and the user stories execpt for receipts

- README.md
- app/views/shared/_navbar.html.erb
> Navbar papel

- app/assets/stylesheets/components/_cards.scss
- app/views/receipts/index.html.erb
> Front index

- app/models/cohort.rb
- app/models/member.rb
- app/models/user.rb
- db/migrate/20200826101318_create_members.rb
- db/migrate/20200826102038_delete_user_from_cohorts.rb
- db/schema.rb
- db/seeds.rb
- test/models/member_test.rb
creation of the model, the references and the seed
> creation members, references and seed

- app/assets/stylesheets/components/_cards.scss
- app/controllers/application_controller.rb
- app/controllers/profile_controller.rb
- app/controllers/receipts_controller.rb
- app/models/user.rb
- app/views/profile/show.html.erb
- app/views/receipts/show.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- test/controllers/profile_controller_test.rb
> profile controller view show

- app/assets/stylesheets/components/_cards.scss
- app/controllers/receipts_controller.rb
- app/views/profile/show.html.erb
> delete profile show

- app/views/profiles/show.html.erb
> front profile

- app/assets/stylesheets/application.scss
- app/views/profiles/show.html.erb
> button profile-to-stats

- app/views/profiles/show.html.erb
- app/views/receipts/new.html.erb
> category fixxing

- app/views/receipts/_form.html.erb
- app/views/receipts/edit.html.erb
- app/views/receipts/new.html.erb
> category fixxing 2

- app/views/receipts/_form.html.erb
> last fixxing

- app/assets/stylesheets/components/_cards.scss
- app/controllers/receipts_controller.rb
- app/views/profiles/show.html.erb
- app/views/receipts/category_list.html.erb
- config/routes.rb
> category list

- app/controllers/cohorts_controller.rb
- app/controllers/members_controller.rb
- app/views/cohorts/show.html.erb
- config/routes.rb
- test/controllers/members_controller_test.rb
> add a new member to a cohort

- app/controllers/profiles_controller.rb
- app/views/profiles/show.html.erb
- app/views/receipts/category_list.html.erb
- app/views/shared/_navbar.html.erb
> categories

- app/assets/stylesheets/components/_cards.scss
- app/views/profiles/show.html.erb
- app/views/receipts/category_list.html.erb
> profile picture

- app/assets/stylesheets/components/_cards.scss
- app/views/profiles/stats.html.erb
> link stats

- app/assets/stylesheets/pages/_cohort.scss
- app/views/cohorts/index.html.erb
> avatar groups

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/pages/home.html.erb
CSS for the home plus fix some problem with the logo and the profil picture navbar
> css for home + fix bug navbar

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/pages/_show_profile.scss
- app/controllers/profiles_controller.rb
- app/models/receipt.rb
- app/views/profiles/show.html.erb
> adding search bar

- app/assets/stylesheets/components/_cards.scss
- app/views/profiles/stats.html.erb
> finish css my expenses

- app/services/text_parser_service.rb
> Sogood receipt

- app/views/profiles/show.html.erb
> ordering tickets
